language: java

services:
          - docker

before_install:
        - docker pull adoptopenjdk/openjdk11:jdk-11.0.3.7


script:
        - docker run --rm -it -v $TRAVIS_BUILD_DIR:/cucumber-example-java -w /cucumber-example-java adoptopenjdk/openjdk11:jdk-11.0.3.7 ./gradlew check
